name: On Change

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Execute custom setup scripts
        run: |
          # Make the script executable
          chmod +x $GITHUB_WORKSPACE/setup-subdirs.sh
          # Run the script with built-in configuration
          $GITHUB_WORKSPACE/setup-subdirs.sh
        working-directory: ${{ github.workspace }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
