name: On Change

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

# Configuration for custom script execution
# Add new entries to this array without changing execution logic
env:
  CUSTOM_SCRIPTS_CONFIG: |
    [
      {
        "directory": "./examples/module4/lesson2/design-tokens",
        "script": "setup.sh"
      }
    ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Execute custom setup scripts
        run: |
          echo "Running custom setup scripts..."
          # Parse the JSON configuration from env variable
          CONFIG_JSON='${{ env.CUSTOM_SCRIPTS_CONFIG }}'

          # Loop through each config entry
          echo "$CONFIG_JSON" | jq -c '.[]' | while read -r entry; do
            DIR=$(echo "$entry" | jq -r '.directory')
            SCRIPT=$(echo "$entry" | jq -r '.script')

            # Check if this directory exists in the repository
            if [ -d "$DIR" ]; then
              echo "Executing script: $SCRIPT for directory: $DIR"
              if [ -f "$SCRIPT" ]; then
                bash "$SCRIPT"
              else
                echo "Warning: Script $SCRIPT not found"
              fi
            fi
          done

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
